### PR TITLE
New: Add and remove buttons and version in footer

### PR DESCRIPTION
**Pull request by rafaelcastrocouto**

### CODE REVIEW

**Comment by devkhan** [comment]
Why wasn't this merged?

**Comment by typicode** [comment]
Mostly for security reasons. If you allow to add commands using hotel API, you need to make sure that it can't be accessed from outside.

By default, hotel runs on 127.0.0.1, so you can't access it. But it's not uncommon for people to make the dashboard accessible for testing on different devices.

So to prevent any possible issue, the only way to add a command is using the terminal.

Also, it's easier to support version manager tools (like nvm) from the terminal, because they modify `PATH` just in terminal.

**Comment by devkhan** [comment]
Thanks for the explanation, but can't we add some kind of a passcode(PIN) authentication for adding new servers from the UI?

**Comment by devkhan** [comment]
Or can this be added as an optional feature which can be toggled from command line?

**Pull request closed without merging**
