### PR TITLE
Allow CORS on SSE

### PR DESCRIPTION
**Pull request by macav**
Hi there,
I would like to add a log viewer into [hotelier](https://github.com/macav/hotelier) and I would need to connect to the `EventSource` from another origin. Would it be possible to integrate this PR so that I can do this?
Thanks!

### CODE REVIEW

**Comment by coorasse** [comment]
As an Hotelier user I'd really ❤️ to see this happening

**Comment by typicode** [comment]
Hi @macav,

Sorry for the delay.

Except if I'm wrong, this mean that any site can call this endpoint. My concern is that technically example.com could read logs from hotel.localhost?

Since it's an Electron app, wouldn't it be possible to use Node code to avoid CORS issue and proxy events via from Hotel to Hotelier API to Hotelier front?

**Comment by macav** [comment]
@typicode thanks for the hint and your time to look into this! I managed to get it working by subscribing to the events in Node and then propagate it to frontend :) I'm closing this one

**Comment by typicode** [comment]
Great :)

**Pull request closed without merging**
