### PR TITLE
Subdomains

### PR DESCRIPTION
**Pull request by alejonext**
Create a support for subdomains

### CODE REVIEW

**Comment by gabpaladino** [comment]
+1

**Comment by typicode** [comment]
Thank you for the PR @alejonext and the feedback @gabpaladino, I'm currently working on viewing server output in the browser (which I hope to release soon) after that I'll focus on subdomains.

**Comment by alejonext** [comment]
Well I know it's basic that I think however this worked.

**Comment by typicode** [comment]
Wildcard subdomains added in `v0.4.12` :)

**Comment by gabpaladino** [comment]
Thanks!! I will test it! :smile:

**Comment by alejonext** [comment]
thanks @typicode !!!

**Pull request closed without merging**
