### PR TITLE
Build before testing on Travis

### PR DESCRIPTION
**Pull request by j-f1**
This should fix the failing test.

### CODE REVIEW

**Comment by j-f1** [comment]
The SCSS file is currently invalid. I have a big PR coming up that will fix this, among other things.

**Comment by typicode** [comment]
Thank you!

> I have a big PR coming up that will fix this, among other things.

Actually, I'm exploring quite a lot on my side as well (trying different JS libs and CSS frameworks) and I don't know yet if it'll end up in a complete rewrite or not :/

So, maybe, it would be better to wait a little bit or not spend too much time.

That said, ideas are welcome and exploring new interfaces is great :) Plus, in case it ends with a rewrite, it would be still possible to have the "classic" interface code as a third-party project that could be server by `hotel`.

**Comment by j-f1** [comment]
> I don't know yet if it'll end up in a complete rewrite or not :/

That’s what I did — It’s in [React](https://reactjs.org/) now, but I’m still using Bulma for the CSS.

**Comment by typicode** [comment]
> That’s what I did — It’s in React now, but I’m still using Bulma for the CSS.

Funny, I have a version in React as well :)

> I’ll open a WIP PR — I’m working on adding a settings button to adjust ~/.hotel/conf.json now.

I've thought about making conf/servers editable from the UI, but I've prefered not to.
If the user changes the host to `0.0.0.0`, then someone else can access the UI, and if you can change servers from the UI, you can run any commands.

For `conf.json`, the risk is a little more limited though I agree. 
Maybe it's too cautious, but for safety I don't think this feature will be part of `hotel`.

**Pull request merged**
