### PR TITLE
Support coloured ANSI output

### PR DESCRIPTION
**Pull request by jalada**
I took the suggestion from @kbariotis on https://github.com/typicode/hotel/issues/65 to use ansi_up. I'm trusting that it does what it says, and strips out unsafe characters, because I'm using triple `{{{ }}}` to set the inner HTML.

It works!

screen shot 2016-04-07 at 12 16 08

### CODE REVIEW

**Comment by jalada** [comment]
Mmm oops. I didn't really want to add the colour toggle in to this pull request but I guess it kinda fits. It's  a matter of taste as to whether you'd like to pull that in too. Let me know. I feel like I vomited all over your JavaScript to get that in (first time I've used Vue.js). Happy to tweak.

colour-flip

**Comment by kbariotis** [comment]
Maaaan, I'm jealous now! I wanted to do that PR. :P Next time for me. :)

**Comment by typicode** [comment]
Thank you 👍 

I'm currently working on subdomains. I'll check that after (I may not keep background toggle though, not sure yet).

BTW, separate PRs are usually easier to merge (for example one to fix the issue with babel-node, another one for ansi-up, ...). But no need to change this PR, it's small enough.

**Comment by jalada** [comment]
@typicode Sorry about that :) I'll make sure to split it up in to pull requests next time. Let me know if it is painful after all and I'll split it up.

**Comment by typicode** [comment]
It'll be ok :) Good job spotting `babel-node` issue.

**Comment by typicode** [comment]
I've decided to use `ansi-html` since it has more downloads on http://npmjs.org and I've added `escape-html` to prevent logs containing HTML to be rendered in the browser.
Hope you don't mind.

By the way, `nodemon` seems actually to be able to load locally installed CLIs.

```sh
~/hotel $ babel-node
bash: /home/typicode/.nvm/versions/node/v5.7.0/bin/babel-node: No such file or directory

~/hotel $ npm run nodemon

> hotel@0.4.19 nodemon /home/typicode/d/hotel
> nodemon -- src/daemon

[nodemon] 1.9.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/daemon`
```

**Pull request closed without merging**
